CHANGELOG
setup.py
test/base_test.py

After [this change](https://github.com/Shopify/pyactiveresource/pull/12) to pyactiveresource, `test_delete_should_send_custom_headers_with_request` was failing due to inconsistent expected and actual URLs. This failure was causing other tests to fail as `shopify.ShopifyResource.set_headers` weren't being reset after the failure.

Fix for prefix issue in base_test.py

---

CHANGELOG
shopify/session.py
test/session_test.py

This PR replaces the soon-to-be-deprecated MD5 method of OAuth validation with the HMAC-SHA256 method described [in the Shopify OAuth documentation](http://docs.shopify.com/api/authentication/oauth#verification).
It includes the addition of a few tests to verify that the HMAC calculation is being performed correctly (based on the examples in the Shopify documentation) and replaces tests verifying the calculation of the `signature` parameter with their `hmac` equivalents.
Has been tested in a live production environment without any problems. This PR closes #84.

Update MD5 Signature validation to HMAC

---

shopify/session.py
test/session_test.py

In some cases, the `params` passed to `validate_hmac` could be in Unicode format. This causes issues for the `hmac.compare_digest` function (see [this similar issue](https://github.com/mitsuhiko/werkzeug/issues/537)).
This issue would not be apparent to any system running Python < 2.7.7, as `compare_digest` isn't available on 2.7.6 and lower.
This PR adds a failing test for the Unicode test and fixes the issue by ensuring both arguments to `compare_digest` are UTF-8 encoded.

Fix unicode buffer issue

---

shopify/session.py
test/session_test.py

@kevinhughes27 for review
Porting https://github.com/Shopify/shopify_api/pull/188 to python.
I ended up using str.replace to escape the same subset of characters, and to make sure the case of the URI escape codes is the same.

Escape ampersand in params or equal in keys before signing with hmac.

---

shopify/resources/image.py
test/image_test.py

As @gavinballard points out, a small change in Image class makes it possible for it to behave just as the Variant class, so I added that code to it, tested on my dev store and wrote a test for it.

Support for independently creating/modifying product images (closes #88)

---

shopify/resources/__init__.py
shopify/resources/location.py
test/fixtures/location.json
test/fixtures/locations.json
test/locations_test.py

Hey guys,
it seems Locations endpoint was missing in the API, and as `shipping_zones`, there was not much trouble in including it.
I have also set up the tests for both collection and single location search

Adds Location module and tests (closes #113)

---

shopify/resources/__init__.py
shopify/resources/recurring_application_charge.py
shopify/resources/usage_charge.py
test/fixtures/recurring_application_charge_adjustment.json
test/fixtures/recurring_application_charges.json
test/fixtures/usage_charge.json
test/fixtures/usage_charges.json
test/recurring_charge_test.py
test/usage_charge_test.py

- adds support for `usage_charge` resource
- adds `#customize` and `#usage_charges` to `recurring_application_charge`
@Shopify/finance @dominiquesr @kevinhughes27 @dylanahsmith

add usage_charge resource and update recurring charge

---

index.md

Hello !
I'm studying the Python and noticed that Python3 support was added in the 2.1.0 version.
Thanks =)

Remove the Python3 limitation

---

.travis.yml
README.md
setup.py
tox.ini

Creates isolated test environments for conveniently testing against multiple Python versions.
The tox configuration here tests against Python 2.7, Python 3.4, Python 3.5, PyPy, and PyPy3 by default. Given that the issues referenced in #114 and #117 have to do with build isolation, this should resolve those issues (have not experienced them, that much I'm certain about).

Add tox for testing and Python 3.5 test support

---

shopify/session.py
test/session_test.py

Removing all references in the code to the deprecated `signature` parameter which is no longer provided by Shopify in the interest of cleaning up the codebase and reducing confusion for partners.
I removed the test for `test_return_token_if_hmac_is_valid_but_signature_also_provided` since its no longer applicable but I wasn't sure about `test_raise_error_if_params_passed_but_signature_omitted` - is this testing if `signature` and `hmac` are omitted?
@kevinhughes27 @dylanahsmith @ShayneP

Removed all references in code to deprecated signature parameter

---

CHANGELOG
shopify/resources/order_risk.py
shopify/version.py

Singular resource name for OrderRisk was previously `order_risk`, as determined by the resource name.
This change updates the resource name to be `risk` (as per the API specification).
Also bumps version to `2.5.1` for release.

Fix order risk resource name

---

.gitignore
.travis.yml
setup.py
tox.ini

This is a really small PR:
- Add the `.tox` output directory to gitignore
- Add Python 3.6 to the list of test environments (just to be sure we support it)

Repo wide nitpicks

---

shopify/resources/__init__.py
shopify/resources/marketing_event.py
test/fixtures/engagement.json
test/fixtures/marketing_event.json
test/fixtures/marketing_events.json
test/marketing_event_test.py

This closes https://github.com/Shopify/merchant-marketing/issues/1645.
This PR adds the MarketingEvent resource, which behaves the same as the [Ruby API client counterpart](https://github.com/Shopify/shopify_api/blob/fcdd350f6652c9f97df5251ffc1fc85cc4de3e94/lib/shopify_api/resources/marketing_event.rb). 
---
```python
>>> shopify.Order.count()
1
>>> shopify.MarketingEvent.count()
0
>>> event = shopify.MarketingEvent()
>>> event.event_type = 'ad'
>>> event.budget = '10.00'
>>> event.currency = 'USD'
>>> event.budget_type = 'lifetime'
>>> event.utm_campaign = 'CanadaDay2016'
>>> event.utm_source = 'facebook'
>>> event.utm_medium = 'cpc'
>>> event.manage_url = 'https://mymarketingapp.com/ad/1234'
>>> event.preview_url = 'https://www.facebook.com/123456/'
>>> event.started_at = …
```

Add MarketingEvent resource

---

shopify/resources/__init__.py
shopify/resources/product_search_engine.py

🔥 ProductSearchEngine since it doesn't exist in the Shopify API.
Closes https://github.com/Shopify/shopify_python_api/issues/206

Remove deprecated ProductSearchEngine

---

shopify/resources/__init__.py
shopify/resources/resource_feedback.py
shopify/resources/storefront_access_token.py
test/fixtures/storefront_access_token.json
test/fixtures/storefront_access_tokens.json
test/resource_feedback_test.py
test/storefront_access_token_test.py

Adds two new resources to the package:
* StorefrontAccessToken
* ResourceFeedback
This PR brings this package to parity (at least in terms of resource inclusion) with the current state of the proper Shopify Admin API.
One minor caveat is that ResourceFeedback will not raise an exception on save for persisted resources ([as it does in the Ruby version of this package](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/resource_feedback.rb#L14-L17)), as `pyactiveresource` would need to be extended to support the `persisted` attribute on resources.
Closes https://github.com/Shopify/shopify_python_api/issues/188 & https://github.com/Shopify/shopify_python_api/issues/185.

Add StorefrontAccessToken and ResourceFeedback

---

README.md

Add an example of a resource with a prefix option to the README.

Add prefix options example to README

---

shopify/resources/image.py
test/image_test.py

As mentioned in #147, `attach_image` from `shopify.image` under Python 3 creates an image object that can't be saved, because the bytes array for the attachment can't be JSON-encoded.  This decodes the bytes back into a plain string.  (In Python 2 this same change seems to work without any complications, since it takes a string object to start with and decodes it into a unicode string containing the same ASCII-only bytes it started with.)
Thanks @pntt.

fix #147: ensure image attachments are strings to be JSON-encodable

---

shopify/session.py
test/session_test.py

- `Session.create_permission_url` `redirect_uri` parameter is now required (#153)
- `Session.create_permission_url` has a new optional `state` parameter (#154)
- added and modified tests to fit the new behavior

Upgrade of `Session.create_permission_url`

---

shopify/resources/asset.py
test/asset_test.py

After upgrading a project to Python 3, attempting to call `attach()` on an `Asset` object would result in the following error: `TypeError: Object of type 'bytes' is not JSON serializable`.
Using the decode method resolves this.

Handle bytes data for asset attachments

---

shopify/resources/refund.py
test/fixtures/refund_calculate.json
test/refund_test.py

As the documentation suggests:
When you want to create a refund, you should first use the calculate
endpoint to generate accurate refund transactions.
This implementation will give us an unsaved refund record. After this you have
to change the transaction kind to "refund" from "suggested_refund" as suggested
in the API documentation.

Implement refund calculation for an order

---

test/collection_listing_test.py
test/discount_code_test.py
test/draft_order_test.py
test/inventory_level_test.py
test/marketing_event_test.py
test/price_rules_test.py
test/product_listing_test.py
test/storefront_access_token_test.py

The test helper accepts the `code` parameter to set the status code in the mock response, but `status` was used in these tests erroneously (probably because that's what matches our test suite in `shopify_api`).
This PR replaces all instances of `status=` with `code=` in the tests.

Use code parameter instead of status when invoking test helpers

---

scripts/shopify_api.py

Use the `six.moves` library to add Python 3 support for the API console while maintaining compatibility for Python 2.
Specifically, the calls to `input()` need to be handled differently in Python 2 & 3 – `raw_input()` is not supported in Python 3.
Also, in Python 2 `map` returns a list but in Python 3 `map` returns an iterator. Using `map` from `six.moves` delegates the call in Python 2 to `itertools.imap()` which also returns an iterator.

Add Python 3 compatibility for API console.

---

shopify/resources/__init__.py
shopify/resources/api_permission.py
test/api_permission_test.py

Adds support for the ApiPermission resource, which allows applications to programmatically uninstall themselves.
See the documentation [here](https://help.shopify.com/en/api/getting-started/authentication/oauth/uninstalling-applications) in the help center for more details.
Closes https://github.com/Shopify/shopify_python_api/issues/158.

Add ApiPermission resource

---

shopify/resources/recurring_application_charge.py
test/recurring_charge_test.py

Closes https://github.com/Shopify/shopify_python_api/issues/190.
The `cancel` endpoint for RecurringApplication Charge doesn't return a body ([source](https://help.shopify.com/en/api/reference/billing/recurringapplicationcharge#destroy)), so `shopify.RecurringApplicationCharge.cancel()` throws an exception whenever its called since it tries to load an instance from the response.
The proper way to cancel a RecurringApplicationCharge is to simply call the `destroy()` method inherited from the parent ActiveResource class as demonstrated [here](https://github.com/Shopify/shopify_python_api/issues/190#issuecomment-427105097).

Remove cancel() method for RecurringApplicationCharge

---

shopify/resources/__init__.py
shopify/resources/discount_code_creation.py
shopify/resources/price_rule.py
test/discount_code_creation_test.py
test/fixtures/batch_discount_codes.json
test/fixtures/discount_code_creation.json
test/price_rules_test.py

Adds support for the [batch operations](https://help.shopify.com/en/api/reference/discounts/discountcode#batch_create)  available in the PriceRule API.
Specifically, this PR:
* adds support for `create_batch()` and `find_batch()` on `shopify.PriceRule`
* adds a new `shopify.DiscountCodeCreation` resource, to represent the resource returned when creating and finding batch jobs
* adds support for `discount_codes()` on `shopify.DiscountCodeCreation`
Closes https://github.com/Shopify/shopify_python_api/issues/250.

Add support for PriceRule batch endpoint

---

shopify/resources/access_scope.py
test/access_scope_test.py

Small fix for the `AccessScope` resource.
The `access_scope` endpoint is prefixed with `/admin/oauth`, so this PR adds the correct prefix.

Add prefix source to AccessScope resource

---

shopify/resources/__init__.py
shopify/resources/tender_transaction.py
test/fixtures/tender_transactions.json
test/tender_transaction_test.py

**Issue**: https://github.com/Shopify/money-transactions/issues/688
As we are preparing to launch the TenderTransaction api, we will need to make it available for use in our SDKs. This PR adds a new TenderTransaction resource as well as a json fixture.
This PR adds a TenderTransaction resource to the library, as well as a json fixture to be used for testing.

Add TenderTransaction resource

---

CHANGELOG
shopify/version.py

Packaging for next release. See CHANGELOG.
== Version 4.0.0
* Added AccessScope resource
* Added ApiPermission resource
* Added User resource
* Added Publication, CollectionPublication and ProductPublication resources
* Added Currency resource
* Added TenderTransaction resource
* Added shopify.Limits class, for retrieving the current status of Shopify rate limiting.
* Added support for Refund.calculate
* Added support for Location.inventory_levels
* Added support for PriceRule batch operations
* Removed `cancel()` method for RecurringApplicationCharge resource (use `destroy()` going forward)
* Fix for handling array query parameters (e.g. `foo[]=1&foo[]=2`) during HMAC calculation
* Fixed Python 3 compatibility with the API console

Package for releasing 4.0.0

---

shopify/version.py

https://github.com/Shopify/shopify_python_api/pull/285 incorrectly bumped the version to 3.2.0 instead of 4.0.0.
Since we are deprecating some features (i.e. removing the `cancel()` method from RecurringApplicationCharge), semver dictates a major version bump.

Bump version to 4.0.0

---

shopify/base.py
shopify/resources/access_scope.py
shopify/resources/api_permission.py
shopify/resources/article.py
shopify/resources/asset.py
shopify/resources/collection_publication.py
shopify/resources/discount_code.py
shopify/resources/discount_code_creation.py
shopify/resources/event.py
shopify/resources/fulfillment.py
shopify/resources/image.py
shopify/resources/location.py
shopify/resources/metafield.py
shopify/resources/order_risk.py
shopify/resources/price_rule.py
shopify/resources/product_publication.py
shopify/resources/refund.py
shopify/resources/resource_feedback.py
shopify/resources/shop.py
shopify/resources/transaction.py
shopify/resources/usage_charge.py
shopify/resources/variant.py

This PR removes all instances of `/admin` from all of the resource definitions and sets up a fallback to `Session.site` to prefix all requests.

Centralize all resource prefix definitions

---

shopify/base.py
test/base_test.py

Adds a missing class var to fix setting site with basic authentication. Closes #311 
@radovansurlak @bputt @muad-dweeb @kayluhb

fix missing class var on ShopifyResource

---

CHANGELOG
README.md
shopify/resources/__init__.py
shopify/resources/graphql.py
shopify/version.py
test/fixtures/graphql.json
test/graphql_test.py

Adds the ability to make GraphQL queries by supplying a query, as documented below. This follows the pattern that we established in Ruby. The test isn't great, we need to add something more robust for GraphQL at some point.
This library also supports Shopify's new [GraphQL API](https://help.shopify.com/en/api/graphql-admin-api). The authentication process (steps 1-5 under Getting Started) is identical. Once your session is activated, simply construct a new graphql client and use `execute` to execute the query.
```
client = shopify.GraphQL()
query = '''
{
shop {
name
id
}
}
'''
result = client.execute(query)
```

Add GraphQL

---

README.md
shopify/base.py
test/base_test.py
test/session_test.py

Fixes #314 
Currently in the README we tell users that are using this library with private app credentials (basic auth) to use the `set_site` method to set their session URL. This method blindly sets the `site` class attribute and is referenced by some resource definitions like [Shop](https://github.com/Shopify/shopify_python_api/blob/master/shopify/resources/shop.py#L10), which results in incorrect URLs being requested. Ideally resources shouldn't have to care about the FQDN/site url when generating code for API Requests, but that's out of scope of this fix.
This fix strips out the `username:password` fragment from the site URL like [the underlying pyactiveresource method](https://github.com/Shopify/pyactiveresource/blob/master/pyactiveresource/connection.py#L218-L233) but retains the …

Fix setting site with basic auth URL

---

scripts/shopify_api.py

shopify_api.py has been broken since version 5.0.0. this fixes it and allows a user to configure API version and define a default if not set, will require pull request #335

Fix shopify_api.py to work with API versions

---

CHANGELOG
shopify/api_version.py
shopify/version.py

Just preemptively getting the 2020-01 release candidate version ready to go in case we don't get dynamic versions checked off prior to the October 1st.  Bumps the egg (wheel? lib?  🐍?) to version 5.1.2.
This version does not exist yet but it will become the release candidate come October. Attempting to use it before October 2019 will result in an unknown version error from the server.

add version 2020-01 to known versions

---

scripts/shopify_api.py

After activating the console via shopify_api.py i could not access local python modules.  I needed to add the current working directory to the sys paths before starting the console.

enable shopify_api.py to load local modules

---

shopify/base.py
shopify/collection.py
test/pagination_test.py

fixes #353 
This allows PaginatedCollection to handle all collections if they have pages or not. This way the interface is more consistent and you have to do fewer checks for types.
@Philpax I believe you asked for this in the original PR as well.

Cast all collections to PaginatedCollection

---

shopify/base.py
shopify/collection.py
test/pagination_test.py

fixes #357 
fixes #356 
This adds 2 things.
It seems like some versions of urlib mess with the case of header names. I have added in flexibility to this to check for Link and link so that it will work in any case
kwargs were not passed to the Paginated collection so there was no way for a user to specify the attribute no_iter_next in the initialization. I have passed along the kwargs now and it can not be specified
@GhostApps @Philpax @dasony for review of changes

Adding some flexibility into the pagination

---

shopify/base.py
shopify/resources/product.py
shopify/resources/variant.py

fixes #347
Hi, I think that PR can solve the problem about updating variants from api versions +2019-10, and the error 400.

Solves API version +2019-10 fails with variant updates

---

shopify/resources/product.py

Shopify API allows not setting all the attributes when changing a resource. It can be used as optimization to speed up things if some parts of a resource doesn't change.
Common scenario is to prevent variants update when saving product as there can be up to 100 variants per product and saving all takes a long time.
Recent update to delete `inventory_quantity` and `old_inventory_quantity` of variants when saving product broke the ability to delete variants to prevent them from saving. It was working fine in version 7.0.0.
This PR adds a check if the `variants` are defined on a product before attempt to delete `inventory_quantity` and `old_inventory_quantity` when saving.

Handle saving of product with no variants specified

---

RELEASING

We've had some cases (e.g. #386) where the README examples are not in sync with the latest API.
Let's add this step as a reminder to validate them.
(Later we can look into automating this).

Update Release notes regarding testing against stable API

---

README.md

Fixes #447 
Updating readme to indicate that charges no longer need to be manually activated in the new API version.

Mention activation charge changes in 2021-01 version

---

CHANGELOG
shopify/version.py

Releasing 8.2.0 with changelog update

Release v8.2.0

---

CHANGELOG
shopify/resources/fulfillment.py
test/fixtures/fulfillment.json
test/fulfillment_test.py

The fulfillment API has a clear method of [updating tracking information ](https://shopify.dev/docs/admin-api/rest/reference/shipping-and-fulfillment/fulfillment#update_tracking-2020-01) that our library doesn't support. 
This may help reduce issues such as #310.
Following the footsteps of shopify_api, a new class was created in order to hit the end point `/fulfillments/$fulfillment_id`

Add update_tracking endpoint to Fulfillment

---

CHANGELOG
scripts/shopify_api.py

Fixes #426 
- previously, the code tried to get the length and index of a `filter`
- if you print out a filter, it will look like this
```
>>> f
<filter object at 0x10b0cedc0>
```
- this filter object has no `len()` attribute
```
>>> len(f)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: object of type 'filter' has no len()
```
- by converting the filter into a list, we will be able to get the length and index of a filter

Fix 'object of type "filter" has no len()' issue in shopify_api.py

---

README.md

- a badge shows users/contributors that we use pre-commit
- add pre-commit badge

Add pre-commit badge to repo

---

README.md
docs/api-access.md
docs/session-tokens.md
shopify/__init__.py
shopify/api_access.py
test/api_access_test.py

There are common operations that are used for managing access scopes in apps. Such operations include serializing, deserializing and normalizing scopes. 
This PR introduces the `ApiAccess` value object that will be used to perform such operations. This helps ensure that apps do not potentially write duplicate code for scopes and delegating this responsibility to the `shopify_python_api`.
For further reference, we made a similar move in the [Shopify API ruby gem](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/api_access.rb)
```python
api_access = ApiAccess(["read_products", "write_orders"])
another_api_access = ApiAccess("read_products, write_products")
```
```python
def scopes_match?(existing_scopes, requesting_scopes)
expected_api_access = ApiAccess(existing_scopes) …
```

Introduce ApiAccess for representing access scopes

---

shopify/api_access.py
shopify/session.py
test/session_test.py

We need to store access scopes in the `Session` object so that apps have access to the scope granted to them after OAuth. These scopes can then be used by apps to keep track of scopes granted.
Storing `access_scopes` as an instance variable in the `Session` object on construction and after access token exchanges.

[Feature]: Add access scopes in Session object

---

CHANGELOG
setup.py
shopify/version.py

> This will also be a patch release 8.3.1
This change introduces a missing `shopify.utils` package inclusion in the library's setup.py file. This will include the `utils` package in the source distribution TAR file as well.
Right now, we get the following error trying to use `shopify.utils`:
```
ModuleNotFoundError: No module named 'shopify.utils'
```
* Add `shopify/utils` as a package for src distribution

[Bug fix] Release v8.3.1: Add shopify/utils to setup.py

---

shopify/utils/shop_url.py
test/utils/shop_url_test.py

> **Bug:** `shop_url.sanitize_shop_domain(None)` returns `"none.myshopify.com"`
> * I just found out that `str(None) == "none"` in Python 😬 
~~This PR is intended to be a patch for shopify_python_api `v8.3`~~. It introduces a check to see if `shop_domain` is `None`.
~~I noticed that we've released `v8.4` already. Ideally, I'd like to release this as a patch for both `v8.4` and `v8.3.2`. Do we have a guide on how to do this?~~
This is intended to be a patch release.

[Bug fix] - Return None when sanitizing shop domain if None passed in

---

CHANGELOG
shopify/version.py

- Bug fix: `sanitize_shop_domain` now correctly returns `None` rather than `'none.myshopify.com'` if no shop domain is passed in ([#499](https://github.com/Shopify/shopify_python_api/pull/499))
Packaging for patch release `v8.4.1`.

Release v8.4.1

---

.github/workflows/build.yml

- there is a codecov token located in the `secrets` of this repo. From the docs we don't need this token and it might pose a security issue in the future 🥴 
- remove the codecov token from the workflow
- I'll remove the secret from the repo once this PR is merged 🎉 
- it is an option to remove codecov fully, but as this is an open-source repo there are not secrets (other than the one I am removing now) that would be affected by future security vulnerabilities

Remove unused codecov secret token

---

README.md
shopify/resources/graphql.py
test/graphql_test.py

When constructing non-trivial GraphQL queries, it can be helpful to have multiple NamedOperations in the same document. 
For example, I could have a fragment which I'd like to reuse between two queries:
```graphql
fragment orderInfo on Order {
id
name
createdAt
}
query GetOneOrder($order_id: ID!){
node(id: $order_id){
...OrderInfo
}
}
query GetManyOrders($order_ids: [ID]!){
nodes(ids: $order_ids){
...OrderInfo
}
}
```
From [the GraphQL docs](https://graphql.org/learn/serving-over-http/#post-request), an "operationName" parameter can be included in the POST request to specify which operation should be performed. 
When sending a manual GraphQL POST request to Shopify, the "operationName" parameter is accepted / respected. 
**Currently**,  
There is no way to specify this operationName as a …

Add operation_name parameter to Graphql.execute

---

CHANGELOG
dev.yml
shopify/api_version.py

Closes #584
Closes #590
This PR removes support for the `2021-07` API version, and adds support for `2022-07`.

Update to 2022-07 release

---

.pre-commit-config.yaml
scripts/shopify_api.py
shopify/api_access.py
shopify/mixins.py
shopify/session.py

Fix: Upgrade pre-commit dependencies to resolve CI failures
Fixes #754 
Pre-commit checks are failing in GitHub Actions with the current dependencies. This is blocking other PRs like #752 and #753.
- Upgrades pre-commit dependencies to their latest versions:
- pylint: v2.15.8 -> v3.3.3
- black: 22.3.0 -> 24.10.0
- pre-commit-hooks: v3.4.0 -> v5.0.0
- Fixes new pylint warnings introduced by the upgrade
If this approach isn't aligned with the project's direction, please let me know and I'll be happy to close this PR.

Fix: Upgrade pre-commit dependencies to resolve CI failures
