Shopify/shopify_python_api

- README.md
Hey! :smile: 
This PR adds a badge for Travis and a badge for PyPi. Nothing fancy.
It also cleans up whitespace.
> Adding Travis and Pypi badges and cleaning up whitespace.

- _layouts/index.html
Typo "ttp://api..." > "https://api..."
> Fixed broken link to documentation

- shopify/resources/customer.py
- test/customer_test.py
- test/fixtures/customer.json
- test/fixtures/customers_search.json
cc @sephii and @kevinhughes27 
I noticed issue #100 and that we are missing customer tests.  Although, I wasn't able to reproduce that specific issue, I thought we should still add those tests.
> Add customer tests

- README.md
Updating README to reflect the changes to ```redirect_uri```, and added the optional ```state``` param.
@kevinhughes27 @awd
> Update README for security changes

- README.md
This addresses [#122](https://github.com/Shopify/shopify_python_api/issues/122).
> Add 'destroy' example to README

- shopify/resources/__init__.py
- shopify/resources/shipping_zone.py
- test/fixtures/shipping_zones.json
- test/shipping_zone_test.py
Hey guys,
This was easier than I thought since most of the heavy lifting is done by pyactiveresource.
Did some basic testing with my dev account and data seems fine
> Adds suport to Shipping Zones (closes #126)

- shopify/resources/__init__.py
- shopify/resources/refund.py
- shopify/version.py
- test/fixtures/refund.json
- test/refund_test.py
Adding refund object to the Python library 🐍 
@kevinhughes27 for 👀
> Add refund

- CHANGELOG
Updating the changelog to prep for release
@kevinhughes27 @jamiemtdwyer
> Release v2.1.6

- CHANGELOG
- shopify/version.py
Updated changelog and `version.py` for release 2.1.7
> Release v2.1.7

- shopify/resources/fulfillment.py
- test/fulfillment_test.py
('nuff said -- let me know if you'd like anything different here)
> Added open method to Fulfillment (and appropriate test case)

- scripts/shopify_api.py
updated bad url for retrieving api credentials
@kevinhughes27 for :eyes:
> Updated instructions for generating api credentials in shopify_api.py

- .gitignore
- shopify/session.py
- test/session_test.py
> if the timestamp is missing, Dont Panic

- CHANGELOG
- shopify/resources/__init__.py
- shopify/resources/customer.py
- shopify/resources/customer_invite.py
- shopify/version.py
- test/customer_test.py
- test/fixtures/customer_invite.json
Adds `CustomerInvite` and exposes `Customer#send_invite`
> Add support for customer invites

- CHANGELOG
- shopify/resources/__init__.py
- shopify/resources/report.py
- shopify/version.py
- test/fixtures/report.json
- test/fixtures/reports.json
- test/report_test.py
> Add support for Report API

- shopify/resources/__init__.py
- shopify/resources/discount_code.py
- shopify/resources/price_rule.py
- test/discount_code_test.py
- test/fixtures/discount_code.json
- test/fixtures/discount_codes.json
- test/fixtures/price_rule.json
- test/fixtures/price_rules.json
- test/price_rules_test.py
Add [Price Rules API](https://help.shopify.com/api/price-rules)
> Price rules implementation

- CHANGELOG
- shopify/version.py
Prepare to release version 2.5.0 which includes support for the Price Rules API and Discount Codes.
> Prepare to release version 2.5.0

- CHANGELOG
- RELEASING
- shopify/version.py
Change log:
* Adds Marketing Event Resource
> Release 2 6

- README.md
> Add advanced usage examples to README

- CHANGELOG
- shopify/version.py
* Added CollectListing resource
* Added ResourceFeedback resource
* Added StorefrontAccessToken resource
* Added ProductListing resource
* Removed deprecated ProductSearchEngine resource
* Removed deprecated Discount resource
* Fixed Python3 compatibility issue with `Image.attach_image()`
> Release v3.0.0

- shopify/resources/__init__.py
- shopify/resources/gift_card.py
- shopify/resources/gift_card_adjustment.py
- test/fixtures/gift_card_adjustment.json
- test/gift_card_test.py
Implements the GiftCardAdjustment API with Tests.
* Adds an `adjust` method on gift card
* Also implements a `search` method on gift card for easy lookup of gift cards
> Implement GiftCardAdjustment API

- shopify/resources/__init__.py
- shopify/resources/inventory_item.py
- shopify/resources/inventory_level.py
- test/fixtures/inventory_item.json
- test/fixtures/inventory_items.json
- test/fixtures/inventory_level.json
- test/fixtures/inventory_levels.json
- test/inventory_item_test.py
- test/inventory_level_test.py
https://help.shopify.com/api/reference/inventory
Implemented:
* Inventory items
* Inventory levels
Location endpoint is already implemented. 
Includes API changes to handle the active resources and tests.
> Inventory API

- shopify/resources/__init__.py
- shopify/resources/access_scope.py
- test/access_scope_test.py
- test/fixtures/access_scopes.json
Add support for the [AccessScope](https://help.shopify.com/en/api/reference/access/accessscope) resource.
> Add AccessScope resource

- shopify/resources/__init__.py
- shopify/resources/currency.py
- test/currency_test.py
- test/fixtures/currencies.json
Adding this endpoint following similar examples as transactions. Docs being updated are here: https://github.com/Shopify/shopify/pull/174966
> Added currency endpoint

- README.md
> Fix broken Markdown when showing Python code snippets.

- shopify/resources/__init__.py
- shopify/resources/collection_publication.py
- shopify/resources/product_publication.py
- shopify/resources/publication.py
- test/collection_publication_test.py
- test/fixtures/collection_publication.json
- test/fixtures/collection_publications.json
- test/fixtures/product_publication.json
- test/fixtures/product_publications.json
- test/fixtures/publications.json
- test/product_publication_test.py
- test/publication_test.py
Adds support for the following API resources:
* Publication
* CollectionPublication
* ProductPublication
> Add Publication, CollecionPublication and ProductPublication resources

- README.md
- shopify/__init__.py
- shopify/api_version.py
- shopify/base.py
- shopify/session.py
- test/access_scope_test.py
- test/api_version_test.py
- test/base_test.py
- test/session_test.py
- test/test_helper.py
> Add API Versioning

- CHANGELOG
- shipit.yml
- shopify/version.py
Praying that adding this shipit.yml will make shipit work. Also releasing v5.1.1.
> Add shipit

- shopify/resources/event.py
- test/event_test.py
> Fixing small string interpolation issue

- shopify/api_version.py
> Fix deprecation warning regarding invalid escape sequences.

- shopify/base.py
fixes #374 
fixes #373 
The fix for updating variants included a small bug that broke temporary sessions.
> Fix for version getter

- shopify/api_version.py
fixes #381 
- Removes 2019-04
+ adds 2020-04
> Update API versions

- shopify/api_version.py
> Update API version

- dev.yml
- requirements.txt
This allow developers using Shopify's internal tooling to get set up more easily on the project.
> Add dev.yml for setup

- README.md
- scripts/shopify_api.py
fixes #372
The readme is 💩  and has always been 💩  and also references a lot of ruby things for some reason. It also does not accurately capture the proper way to authenticate, or validate the authentication.
- Updating readme 
- authentication process
- graphql access
- removing unnecessary information
- making some of it a bit more clear
- Fixing the console setup process so that console running is easier
> Updating README

- .github/PULL_REQUEST_TEMPLATE.md
To help avoid missing entries such as https://github.com/Shopify/shopify_python_api/pull/421
> Add changelog reminder to pull request template

- README.md
My bad, just noticed that the added note is in the wrong step.
> Move note to right step

- README.md
The old link for adding an app was broken
Also fix spelling of retrieve
> Update links to Partners Dashboard

- CHANGELOG
- shopify/resources/__init__.py
- shopify/resources/application_credit.py
- test/application_credit_test.py
- test/fixtures/application_credit.json
- test/fixtures/application_credits.json
- test/fulfillment_event_test.py
Fixes #343
- introduce new resource ApplicationCredit that maps the the [application_credit api](https://shopify.dev/docs/admin-api/rest/reference/billing/applicationcredit)
> Add application credit

- .github/workflows/build.yml
- README.md
- need a way to see code coverage
- implement codecov
> Add codecov to measure code coverage across repo

- .github/workflows/build.yml
- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- CHANGELOG
- README.md
- shopify/resources/fulfillment.py
- test/blog_test.py
- test/cart_test.py
- test/checkout_test.py
- test/customer_saved_search_test.py
- test/fixtures/carts.json
- test/fixtures/price_rules.json
- test/fulfillment_test.py
- test/graphql_test.py
- test/shipping_zone_test.py
- test/variant_test.py
- this PR follows #463
- added the `trailing-whitespace` hook which trims trailing whitespace
- ran `pre-commit run --all-files`
> Add trailing-whitespace hook and run on all files

- shopify/session_token.py
- shopify/utils/shop_url.py
- test/utils/shop_url_test.py
> Depends on https://github.com/Shopify/shopify_python_api/pull/479
This PR adds a `sanitize_shop_domain` utility method that can be used repeatedly throughout the lifecycle of an app's Oauth with Shopify.
This implementation has been ported from the shopify_app gem: https://github.com/Shopify/shopify_app/blob/17138d7d29d0c85d8f38ace981cac5f726b68833/lib/shopify_app/utils.rb#L4-L14
```py
def sanitize_shop_domain(shop_domain, myshopify_domain="myshopify.com"):
"""Returns a sanitized Shopify shop domain.
If the provided shop domain is invalid or could not be sanitized, returns None.
Parameters:
shop_domain: str
A fully-qualified Shopify shop domain or hostname
myshopify_domain: str, optional
A custom Shopify domain
Examples:
>>> print(sanitize_shop_domain('my-shop'))
'my-shop.myshopify.com' …
```
> [Feature] Add sanitize shop param utility

- CHANGELOG
- shopify/version.py
This is packaging for release `v8.3.0`
> Taken from the CHANGELOG
**Version 8.3.0**
- Add support for [session tokens](https://shopify.dev/concepts/apps/building-embedded-apps-using-session-tokens) ([#479](https://github.com/Shopify/shopify_python_api/pull/479))
- Use `session_token.decode_from_header` to obtain a decoded session token from an HTTP Authorization header
- Create a `utils` sub-package with a `shop_url` utility file ([#483](https://github.com/Shopify/shopify_python_api/pull/483))
- Use `shop_url.sanitize_shop_domain()` to sanitize shop names given as input
- Introduce the `ApiAccess` class to handle access scopes operations for apps
- `Session` class now store access_scopes attributes as `ApiAccess` objects
- Added support for Fulfillment.update_tracking …
> Release v8.3.0

- CHANGELOG
- shopify/version.py
> Release v8.4.0

- .github/api_update_reminder.md
- .github/api_update_reminder_on_release.md
- .github/workflows/api_update_reminder.yml
- .github/workflows/api_update_reminder_on_release.yml
> Add automated reminder for API updates

- .github/api_update_reminder.md
- .github/api_update_reminder_on_release.md
- .github/workflows/api_update_reminder.yml
- .github/workflows/api_update_reminder_on_release.yml
> Allow manual trigger of workflow

- .github/dependabot.yml
> Edit dependabot file

- CHANGELOG
- shopify/version.py
Packaging for release 8.4.2: update api versioning
> Release v8.4.2

- CHANGELOG
- shopify/api_version.py
> Update to 2021-10 release

- CHANGELOG
- shopify/api_version.py
Closes https://github.com/Shopify/shopify_python_api/issues/556, closes https://github.com/Shopify/shopify_python_api/issues/560  
Updating the python release
> Add 2022-01 to api version

- .pre-commit-config.yaml
- CHANGELOG
- shopify/api_version.py
- shopify/yamlobjects.py
- test/base_test.py
Closes https://github.com/Shopify/shopify_python_api/issues/577
Updating the accepted API versions
> Add version 2022-04, remove 2020-10-2021-04

- CHANGELOG
- shopify/api_version.py
> Update API version to 2022-10

- .github/workflows/pre-commit.yml
- CHANGELOG
- shopify/api_version.py
- test/session_token_test.py
This PR adds support for missing API versions.
> Add support for missing API versions

- CHANGELOG
- shopify/api_version.py
> Add support for April24 API version
